#!/bin/bash

file1=$1
file2=$2

touch $file1
touch $file2

while [ 1 ]
do
    read breaker # variable breaker
    if [[ $breaker != "" ]]
    then 
        break
    fi
    read line1 # variable line1
    if [[ $line1 == "" ]]
    then
        break
    fi
    read line2 # variable line2
    if [[ $line2 == "" ]]
    then
        break
    fi

    echo "$line1" >> $file1
    echo "$line2" >> $file2
done
